# Regression Problem

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/instituteofai/ML-101/master/Datasets/cal_housing.csv')

In [3]:
df.head()

   longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [4]:
df.shape

(20640, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [6]:
df.describe()

          longitude      latitude  ...  median_income  median_house_value
count  20640.000000  20640.000000  ...   20640.000000        20640.000000
mean    -119.569704     35.631861  ...       3.870671       206855.816909
std        2.003532      2.135952  ...       1.899822       115395.615874
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.800000     33.930000  ...       2.563400       119600.000000
50%     -118.490000     34.260000  ...       3.534800       179700.000000
75%     -118.010000     37.710000  ...       4.743250       264725.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [7]:
labels = df[['median_house_value']]
labels.head()

   median_house_value
0            452600.0
1            358500.0
2            352100.0
3            341300.0
4            342200.0

In [8]:
features = df[['population', 'total_rooms']]
features.head()

   population  total_rooms
0       322.0        880.0
1      2401.0       7099.0
2       496.0       1467.0
3       558.0       1274.0
4       565.0       1627.0

In [9]:
from sklearn.model_selection import train_test_split
# it will return four variables, X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.15)

In [10]:
X_train.shape, X_test.shape

((17544, 2), (3096, 2))

In [11]:
y_train.shape, y_test.shape

((17544, 1), (3096, 1))

In [12]:
from sklearn import linear_model

In [13]:
model = linear_model.LinearRegression()

In [14]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
from sklearn.metrics import r2_score

In [16]:
predictions = model.predict(X_train)

In [17]:
r2 = r2_score(y_train, predictions)
print("R2 Score :", r2)

R2 Score : 0.09940453025180485

In [18]:
predictions = model.predict(X_test)

r2 = r2_score(y_test, predictions)
print("R2 Score :", r2)

R2 Score : 0.03963271809562052

## Try 2
Lets try to add more features

In [19]:
features = df[['longitude', 'latitude', 	'housing_median_age', 	'total_rooms', 	'total_bedrooms', 	'population', 	'households', 	'median_income']]
features.head()

   longitude  latitude  ...  households  median_income
0    -122.23     37.88  ...       126.0         8.3252
1    -122.22     37.86  ...      1138.0         8.3014
2    -122.24     37.85  ...       177.0         7.2574
3    -122.25     37.85  ...       219.0         5.6431
4    -122.25     37.85  ...       259.0         3.8462

[5 rows x 8 columns]

In [20]:
labels = df[['median_house_value']]
labels.head()

   median_house_value
0            452600.0
1            358500.0
2            352100.0
3            341300.0
4            342200.0

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.15)

In [22]:
X_train.shape, X_test.shape

((17544, 8), (3096, 8))

In [23]:
y_train.shape, y_test.shape

((17544, 1), (3096, 1))

In [24]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [25]:
features = df[['longitude', 'latitude', 	'housing_median_age', 	'total_rooms', 	'population', 	'households', 	'median_income']]
features.head()

   longitude  latitude  ...  households  median_income
0    -122.23     37.88  ...       126.0         8.3252
1    -122.22     37.86  ...      1138.0         8.3014
2    -122.24     37.85  ...       177.0         7.2574
3    -122.25     37.85  ...       219.0         5.6431
4    -122.25     37.85  ...       259.0         3.8462

[5 rows x 7 columns]

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.15)

In [27]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
predictions = model.predict(X_train)

r2 = r2_score(y_train, predictions)
print("R2 Score :", r2)

R2 Score : 0.6267452920125036

In [29]:
predictions = model.predict(X_test)

r2 = r2_score(y_test, predictions)
print("R2 Score :", r2)

R2 Score : 0.6623410593167336